default:
  image: salesforce/cli:latest-slim
  timeout: 10m
  tags:
    - gitlab-org-docker

variables:
  SF_USE_GENERIC_UNIX_KEYCHAIN: true
  SF_IMPROVED_CODE_COVERAGE: true
  SF_HIDE_RELEASE_NOTES: true
  SF_DISABLE_TELEMETRY: true
  SF_CONTAINER_MODE: true
  SF_DISABLE_AUTOUPDATE: true
  SF_LOG_LEVEL: warn

stages:
  - code analysis
  - validation
  - deploy

code analysis:
  stage: code analysis
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
  script:
    # Install code-analyzer plugin
    - |
      if ! sf plugins | grep -q code-analyzer; then
        sf plugins install code-analyzer@latest
      fi

    - echo "Starting code analyses..."
    - sf code-analyzer run
      --workspace ./force-app/main
      --workspace ./force-app/utils/shared
      --rule-selector Recommended
      --rule-selector sfge
      --severity-threshold 3
      --config-file config/code-analyzer.yml
      --view detail

validate deploy:
  stage: validation
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
  script:
    # Download secure files for authentication
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

    - echo "Authenticating with Salesforce..."
    - ./scripts/authenticateWithSalesforce.sh
    
    - |
      trap 'sf org delete scratch --target-org ScratchOrg --no-prompt || true' EXIT

      echo "Creating a scratch org..."
      sf org create scratch \
        --definition-file config/project-scratch-def.json \
        --alias ScratchOrg \
        --target-dev-hub Playground \
        --no-track-source \
        --duration-days 1 \
        --wait 10

      echo "Deploying source code..."
      sf project deploy start \
        --target-org ScratchOrg \
        --wait 10

      echo "Running apex and flow tests..."
      sf logic run test \
        --test-level RunLocalTests \
        --synchronous \
        --target-org ScratchOrg \
        --wait 10

deploy:
  stage: deploy
  environment: Playground
  coverage: '/Org Wide Coverage\s+(\d+(?:\.\d+)?)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura.xml
    paths:
      - package/package.xml
      - destructiveChanges/destructiveChanges.xml
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    # Install the git-delta plugin for source delta management
    - |
      if ! sf plugins | grep -q sfdx-git-delta; then
        echo y | sf plugins install sfdx-git-delta@latest
      fi

    # Create packages for deployment
    - sf sgd source delta --to HEAD --from HEAD~1 --output-dir .

    - |
      # Check if there are components to deploy
      if ! grep -q "<types>" package/package.xml; then
        echo "No components to deploy. Skipping deploy step."
        exit 0
      fi

    # Download secure files for authentication
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

    - echo "Authenticating with Salesforce..."
    - ./scripts/authenticateWithSalesforce.sh

    - echo "Running package deploy..."
    - sf project deploy start
      --manifest package/package.xml
      --post-destructive-changes destructiveChanges/destructiveChanges.xml
      --test-level RunLocalTests
      --ignore-warnings
      --coverage-formatters cobertura
      --results-dir .

    # Extract and print coverage for GitLab
    - |
      COVERAGE=$(grep -oP 'line-rate="\K[0-9\.]+' coverage/cobertura.xml | head -n 1)
      COVERAGE_PERCENT=$(awk "BEGIN { printf \"%.2f\", $COVERAGE * 100 }")
      echo "Org Wide Coverage ${COVERAGE_PERCENT}%"
