before_script:
 # Setup SFDX environment variables
 - export SF_AUTOUPDATE_DISABLE=false
 - export SF_USE_GENERIC_UNIX_KEYCHAIN=true
 - export SF_DOMAIN_RETRY=300
 - export SFDX_DISABLE_APP_HUB=true
 - export SF_LOG_LEVEL=debug
 - export ROOTDIR=force-app/main/default/
 - export ORG_ALIAS=Playground
 - export PACKAGEVERSION=""

stages:
  - code analysis
  - deploy

default:
  image: salesforce/cli:latest-slim
  timeout: 15m
  tags:
    - gitlab-org-docker

code-analysis:
  stage: code analysis
  environment: Playground
  script:
    - sf plugins install code-analyzer
    - sf code-analyzer run --rule-selector pmd:Recommended:$PWD_THRESHOLD_LEVEL --severity-threshold $PWD_THRESHOLD_LEVEL --config-file code-analyzer.yml --view detail

deploy:
  stage: deploy
  environment: Playground
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    # Install sf delta plugin
    - sf plugins install sfdx-git-delta

    # Download secure files from repository
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

    # Authenticate org
    - sf org login jwt --username $SF_USERNAME --jwt-key-file .secure_files/server.key --client-id $SF_CONSUMER_KEY --instance-url https://login.salesforce.com --alias $ORG_ALIAS --set-default

    # Create packages for deployment
    - sf sgd source delta --to "HEAD" --from "HEAD~1" --output-dir "."
    
    # Send package to validation process. If all tests passes, the package is deployed to the stage org
    - sf project deploy start -o $ORG_ALIAS -l RunLocalTests -x package/package.xml --post-destructive-changes destructiveChanges/destructiveChanges.xml --ignore-warnings