before_script:
  - export SF_AUTOUPDATE_DISABLE=false
  - export SF_USE_GENERIC_UNIX_KEYCHAIN=true
  - export SF_DOMAIN_RETRY=300
  - export SFDX_DISABLE_APP_HUB=true
  - export SF_LOG_LEVEL=debug
  - export ROOTDIR=force-app/main/default/
  - export LOGIN_URL=https://login.salesforce.com
  - export ORG_ALIAS=Playground
  - export SERVER_KEY_FILE=.secure_files/server.key
  - export PACKAGEVERSION=""

variables:
  GIT_DEPTH: 0

stages:
  - code analysis
  - test
  - deploy

default:
  image: salesforce/cli:latest-slim
  timeout: 15m
  tags:
    - gitlab-org-docker

code-analysis:
  stage: code analysis
  environment: Playground
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
      when: always
  script:
    - sf plugins install code-analyzer@latest

    - echo "🔍 Starting code analyses..."
    - sf code-analyzer run \
      --rule-selector all:Recommended:1
      --rule-selector all:Recommended:2
      --rule-selector all:Recommended:3
      --rule-selector sfge
      --severity-threshold $SEVERITY_THRESHOLD_LEVEL
      --config-file code-analyzer.yml
      --view detail

test:
  stage: test
  environment: Playground
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
      when: always
  coverage: '/Org Wide Coverage\s+(\d+)%/'
  script:
    # Download secure files for authentication
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

    - echo "🔐 Authenticating with Salesforce..."
    - ./scripts/authenticateWithSalesforce.sh

    - echo "🧪 Running tests...
    - sf apex test run
      --result-format human
      --code-coverage
      --synchronous


deploy:
  stage: deploy
  environment: Playground
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
  artifacts:
    expose_as: 'code coverage'
    paths:
      - package/package.xml
      - destructiveChanges/destructiveChanges.xml
      - deploy-result.json
    expire_in: 15 days
  script:
    # Download secure files for authentication
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

    # Install the git-delta plugin for source delta management
    - echo 'y' | sf plugins install sfdx-git-delta

    # Create packages for deployment
    - sf sgd source delta --to "HEAD" --from "origin/master" --output-dir "."

    - |
      # Check if there are components to deploy
      if ! grep -q "<types>" package/package.xml; then
        echo "No components to deploy. Skipping deployment step."
        exit 0
      fi

    - echo "🔐 Authenticating with Salesforce..."
    - ./scripts/authenticateWithSalesforce.sh

    - echo "📦 Running package deploy..."
    - sf project deploy start
        --manifest package/package.xml
        --post-destructive-changes destructiveChanges/destructiveChanges.xml
        --ignore-warnings
        --json > deploy-result.json