import { createElement } from 'lwc';
import AccountDetails from 'c/accountDetails';
import { getRecord, updateRecord } from 'lightning/uiRecordApi';
import { ShowToastEventName } from 'lightning/platformShowToastEvent';

// Mock the getRecord and updateRecord functions
jest.mock('lightning/uiRecordApi', () => ({
    getRecord: jest.fn(),
    updateRecord: jest.fn()
}));

describe('c-account-details', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-account-details', {
            is: AccountDetails
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });

    it('Verify that the component renders account details correctly', () => {
        // Arrange
        const element = createElement('c-account-details', {
            is: AccountDetails
        });

        // Mock data for getRecord
        const mockData = {
            id: '0011t00000VtU8yAAF',
            apiName: 'Account',
            fields: {
                Name: { value: 'Test Account' },
                Type: { value: 'Prospect' },
                CreatedDate: { value: '2023-01-01' }
            }
        };
        getRecord.mockResolvedValue(mockData);

        // Act
        document.body.appendChild(element);

        // Assert
        return Promise.resolve().then(() => {
            const nameInput = element.shadowRoot.querySelector('lightning-input[data-field="Name"]');
            const typeInput = element.shadowRoot.querySelector('lightning-input[data-field="Type"]');
            expect(nameInput.value).toBe('Test Account');
            expect(typeInput.value).toBe('Prospect');
        });
    });

    it('Verify that the component handles errors correctly', () => {
        // Arrange
        const element = createElement('c-account-details', {
            is: AccountDetails
        });

        // Mock error for getRecord
        getRecord.mockRejectedValue(new Error('Error loading account'));

        // Act
        document.body.appendChild(element);

        // Assert
        return Promise.resolve().then(() => {
            const errorText = element.shadowRoot.querySelector('.slds-text-color_error');
            expect(errorText.textContent).toBe('Error loading account');
        });
    });

    it('Verify that the component calls updateRecord when the Save button is clicked', () => {
        // Arrange
        const element = createElement('c-account-details', {
            is: AccountDetails
        });

        // Mock data for getRecord
        const mockData = {
            id: '0011t00000VtU8yAAF',
            apiName: 'Account',
            fields: {
                Name: { value: 'Test Account' },
                Type: { value: 'Prospect' },
                CreatedDate: { value: '2023-01-01' }
            }
        };
        getRecord.mockResolvedValue(mockData);
        updateRecord.mockResolvedValue({});

        // Act
        document.body.appendChild(element);

        // Simulate button click
        const button = element.shadowRoot.querySelector('lightning-button');
        button.click();

        // Assert
        return Promise.resolve().then(() => {
            expect(updateRecord).toHaveBeenCalledWith({
                fields: {
                    Id: '0011t00000VtU8yAAF',
                    Name: 'Test Account',
                    Type: 'Prospect'
                }
            });
        });
    });

    it('Verify that the component dispatches a toast event on successful save', () => {
        // Arrange
        const element = createElement('c-account-details', {
            is: AccountDetails
        });

        // Mock data for getRecord
        const mockData = {
            id: '0011t00000VtU8yAAF',
            apiName: 'Account',
            fields: {
                Name: { value: 'Test Account' },
                Type: { value: 'Prospect' },
                CreatedDate: { value: '2023-01-01' }
            }
        };
        getRecord.mockResolvedValue(mockData);
        updateRecord.mockResolvedValue({});

        // Add event listener for toast event
        const toastHandler = jest.fn();
        element.addEventListener(ShowToastEventName, toastHandler);

        // Act
        document.body.appendChild(element);

        // Simulate button click
        const button = element.shadowRoot.querySelector('lightning-button');
        button.click();

        // Assert
        return Promise.resolve().then(() => {
            expect(toastHandler).toHaveBeenCalledWith(
                expect.objectContaining({
                    detail: {
                        title: 'Success',
                        message: 'Account updated successfully.',
                        variant: 'success'
                    }
                })
            );
        });
    });

    it('Verify that the component dispatches a toast event on failed save', () => {
        // Arrange
        const element = createElement('c-account-details', {
            is: AccountDetails
        });

        // Mock data for getRecord
        const mockData = {
            id: '0011t00000VtU8yAAF',
            apiName: 'Account',
            fields: {
                Name: { value: 'Test Account' },
                Type: { value: 'Prospect' },
                CreatedDate: { value: '2023-01-01' }
            }
        };
        getRecord.mockResolvedValue(mockData);
        updateRecord.mockRejectedValue({ body: { message: 'Error updating account' } });

        // Add event listener for toast event
        const toastHandler = jest.fn();
        element.addEventListener(ShowToastEventName, toastHandler);

        // Act
        document.body.appendChild(element);

        // Simulate button click
        const button = element.shadowRoot.querySelector('lightning-button');
        button.click();

        // Assert
        return Promise.resolve().then(() => {
            expect(toastHandler).toHaveBeenCalledWith(
                expect.objectContaining({
                    detail: {
                        title: 'Error',
                        message: 'Error updating account: Error updating account',
                        variant: 'error'
                    }
                })
            );
        });
    });
});