name: Deploy to Playground

on:
  push:
    branches:
      - master

env:
  SF_TEMP_SHOW_SECRETS: true
  SF_USE_GENERIC_UNIX_KEYCHAIN: true
  SF_IMPROVED_CODE_COVERAGE: true
  SF_HIDE_RELEASE_NOTES: true
  SF_DISABLE_TELEMETRY: true
  SF_CONTAINER_MODE: true
  SF_DISABLE_AUTOUPDATE: true
  SF_LOG_LEVEL: warn

jobs:
  deploy:
    name: Deploy Package Delta
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    steps:
      - name: Checkout Source Code (Full History)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Safe Directory & Fetch Branches
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --prune --unshallow || git fetch --all

      - name: Install sfdx-git-delta
        run: |
          if ! sf plugins | grep -q sfdx-git-delta; then
            echo y | sf plugins install sfdx-git-delta@latest
          fi

      - name: Generate Delta Package
        run: sf sgd source delta --to HEAD --from HEAD~1 --output-dir .

      - name: Check Package Content
        id: check_package
        run: |
          if ! grep -q "<types>" package/package.xml; then
            echo "No components to deploy. Skipping deploy step."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate Salesforce
        if: steps.check_package.outputs.has_changes == 'true'
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key

          sf org login jwt \
            --username ${{ secrets.SF_USERNAME }} \
            --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --jwt-key-file server.key \
            --instance-url https://login.salesforce.com \
            --set-default

      - name: Deploy Delta Package to Org
        if: steps.check_package.outputs.has_changes == 'true'
        run: |
          sf project deploy start \
            --manifest package/package.xml \
            --post-destructive-changes destructiveChanges/destructiveChanges.xml \
            --test-level RunLocalTests \
            --ignore-warnings \
            --coverage-formatters cobertura \
            --results-dir .

      - name: Print Coverage Output
        if: steps.check_package.outputs.has_changes == 'true'
        run: |
          COVERAGE=$(grep -oP 'line-rate="\K[0-9\.]+' coverage/cobertura.xml | head -n 1)
          COVERAGE_PERCENT=$(awk "BEGIN { printf \"%.2f\", $COVERAGE * 100 }")
          echo "Org Wide Coverage ${COVERAGE_PERCENT}%"
